apiVersion: v1
kind: Service
metadata:
  name: d1-frontend-svc
  namespace: tiendas-d1
  labels:
    app.kubernetes.io/name: d1-frontend-svc
    app.kubernetes.io/part-of: tiendas-d1
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: d1-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
