apiVersion: v1
kind: Secret
metadata:
  name: tiendas-d1-secrets
  namespace: tiendas-d1
  labels:
    app.kubernetes.io/name: tiendas-d1
type: Opaque
stringData:
  DB_PASSWORD: "D1-SecurePassword2026!"
  API_SIGNING_KEY: "d1-super-secret-signing-key-bogota"
  CLOUD_TRACE_KEY: "trace-internal-token-secret"
