apiVersion: v1
kind: Secret
metadata:
  name: retail-secret
  namespace: retail-store
  labels:
    app.kubernetes.io/part-of: retail-platform-2026
type: Opaque
stringData:
  DATABASE_URL: "postgresql://retail_app:Secr3tCl0ud2026@10.0.1.5:5432/retail_db"
  API_KEY: "gcp-retail-enterprise-internal-key-2026"
